#ifndef PQ_RANGE_INCLUDED
#define PQ_RANGE_INCLUDED

enum PQ_RANGE_TYPE {
  PQ_QUICK_SELECT_NONE,
  PQ_RANGE_SELECT,
  PQ_RANGE_SELECT_DESC,
  PQ_SKIP_SCAN_SELECT,
  PQ_GROUP_MIN_MAX_SELECT,
  PQ_INDEX_MERGE_SELECT,
  PQ_ROR_INTERSECT_SELECT,
  PQ_ROR_UNION_SELECT,
  PQ_QUICK_SELECT_INVALID
};

#endif /* PQ_RANGE_INCLUDED */
